name: 'Greeting'
description: 'Greet a person and record the time'
inputs:
  person-name:
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  time:
    description: 'The time we greeted you'
runs:
  using: 'node16'
  main: 'index.js'
